// Code generated by hertz generator.

package user

import (
	"Refined_service/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/spf13/viper"
)

var jwt = middleware.AuthInit(viper.GetString("jwt.secretkey"))

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.MiddlewareFunc(),
	}
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.MiddlewareFunc(),
	}
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}
