// Code generated by hertz generator.

package main

import (
	"Refined_service/biz/config"
	"Refined_service/biz/dal"
	_ "Refined_service/docs"
	"fmt"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/logger/accesslog"
	_ "github.com/hertz-contrib/swagger"
	"github.com/spf13/viper"
	_ "github.com/swaggo/files"
	"time"
)

func main() {
	defer func() {
		err := viper.WriteConfig()
		if err != nil {
			panic(fmt.Errorf("Fatal error in saving config file: %s\n", err))
		}
	}()
	config.Init()
	dal.Init()
	address := viper.GetString("server.host") + ":" + viper.GetString("server.port")
	h := server.New(server.WithHostPorts(address))
	h.Name = "Refined Server"

	//Recovery
	h.Use(recovery.Recovery())
	//Gzip
	h.Use(gzip.Gzip(gzip.DefaultCompression, gzip.WithExcludedExtensions([]string{".svg"})))
	//CORS
	h.Use(cors.New(cors.Config{
		AllowOrigins:     []string{"*"},
		AllowMethods:     []string{"GET,PUT,POST,DELETE"},
		AllowHeaders:     []string{"*"},
		ExposeHeaders:    []string{"*"},
		AllowCredentials: true,
		MaxAge:           12 * time.Hour,
	}))
	//Logger
	h.Use(accesslog.New())

	//Router
	h.Static("/static", "./")
	register(h)
	h.Spin()
}
