// Code generated by hertz generator.

package main

import (
	handler "Refined_service/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
)

func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler, swagger.URL("http://localhost:8022/swagger/doc.json")))
}
