// Code generated by hertz generator.

package comment

import (
	"Refined_service/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/spf13/viper"
)

var jwt = middleware.AuthInit(viper.GetString("jwt.secretkey"))

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.MiddlewareFunc(),
	}
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.MiddlewareFunc(),
	}
}

func _updatecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	return nil
}

func _createcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}
