// Code generated by hertz generator.

package comment

import (
	"context"

	comment "Refined_service/biz/model/comment"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UpdateComment .
// @router /v1/comment/update/:id [PUT]
func UpdateComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.UpdateCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(comment.UpdateCommentResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteComment .
// @router /v1/comment/delete/:id [DELETE]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.DeleteCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(comment.DeleteCommentResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryComment .
// @router /v1/comment/query/ [GET]
func QueryComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.QueryCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(comment.QueryCommentResponse)

	c.JSON(consts.StatusOK, resp)
}
