// Code generated by hertz generator.

package stat

import (
	"Refined_service/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/spf13/viper"
)

var jwt = middleware.AuthInit(viper.GetString("jwt.secretkey"))

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _statMw() []app.HandlerFunc {
	return nil
}

func _querystatMw() []app.HandlerFunc {
	// your code...
	return nil
}
