// Code generated by hertz generator.

package post

import (
	"Refined_service/biz/middleware"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/spf13/viper"
)

var jwt = middleware.AuthInit(viper.GetString("jwt.secretkey"))

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.MiddlewareFunc(),
	}
}

func _createpostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.MiddlewareFunc(),
	}
}

func _deletepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querypostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		jwt.MiddlewareFunc(),
	}
}

func _updatepostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _viewMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _viewpostMw() []app.HandlerFunc {
	// your code...
	return nil
}
