info:
  contact: { }
paths:
  /v1/comment/create/:
    post:
      parameters:
        - description: 作者
          in: body
          name: author
          required: true
          schema:
            type: string
        - description: 内容
          in: body
          name: content
          required: true
          schema:
            type: string
        - description: 所属文章id
          in: body
          name: postID
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses: { }
      summary: 创建评论
  /v1/comment/delete/:id:
    delete:
      parameters:
        - description: 评论id
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses: { }
      summary: 删除评论
  /v1/comment/query/:
    get:
      parameters:
        - description: 文章ID
          in: body
          name: id
          required: true
          schema:
            type: string
        - description: 页码
          in: body
          name: page
          required: true
          schema:
            type: string
        - description: 页面大小
          in: body
          name: page_size
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses: { }
      summary: 查询评论
  /v1/comment/update/:id:
    put:
      parameters:
        - description: 作者
          in: body
          name: author
          required: true
          schema:
            type: string
        - description: 内容
          in: body
          name: content
          required: true
          schema:
            type: string
        - description: 所属文章id
          in: body
          name: postID
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses: { }
      summary: 更新评论
  /v1/post/create/:
    post:
      parameters:
        - description: 标题
          in: body
          name: title
          required: true
          schema:
            type: string
        - description: md内容
          in: body
          name: content
          required: true
          schema:
            type: string
        - description: 作者
          in: body
          name: author
          required: true
          schema:
            type: string
        - description: 日期(YYYY-MM-DD)
          in: body
          name: date
          required: true
          schema:
            type: string
        - description: 标签(,分隔)
          in: body
          name: tags
          required: true
          schema:
            type: string
        - description: 头图url
          in: body
          name: image_url
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses: { }
      summary: 创建文章
  /v1/post/delete/:id:
    delete:
      parameters:
        - description: 文章id
          in: path
          name: id
          required: true
          type: string
      responses: { }
      summary: 删除文章
  /v1/post/query/:
    get:
      parameters:
        - description: 文章id(可选)
          in: query
          name: id
          type: string
        - description: 页码
          in: query
          name: page
          required: true
          type: string
        - description: 页面大小
          in: query
          name: page_size
          required: true
          type: string
      responses: { }
      summary: 查询文章
  /v1/post/update/:id:
    put:
      parameters:
        - description: 标题
          in: body
          name: title
          required: true
          schema:
            type: string
        - description: md内容
          in: body
          name: content
          required: true
          schema:
            type: string
        - description: 作者
          in: body
          name: author
          required: true
          schema:
            type: string
        - description: 日期(YYYY-MM-DD)
          in: body
          name: date
          required: true
          schema:
            type: string
        - description: 标签(,分隔)
          in: body
          name: tags
          required: true
          schema:
            type: string
        - description: 头图url
          in: body
          name: image_url
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses: { }
      summary: 更新文章
  /v1/post/view/:id:
    get:
      parameters:
        - description: 文章id
          in: path
          name: id
          required: true
          type: string
      responses: { }
      summary: 增加浏览量
  /v1/user/create/:
    post:
      parameters:
        - description: 用户名
          in: body
          name: username
          required: true
          schema:
            type: string
        - description: 密码
          in: body
          name: password
          required: true
          schema:
            type: string
        - description: 昵称
          in: body
          name: nickname
          required: true
          schema:
            type: string
        - description: Email
          in: body
          name: email
          required: true
          schema:
            type: string
        - description: 手机号
          in: body
          name: phone
          schema:
            type: string
      produces:
        - application/json
      responses: { }
      summary: 创建用户
  /v1/user/delete/:id:
    delete:
      parameters:
        - description: 用户ID
          in: path
          name: id
          required: true
          type: string
      produces:
        - application/json
      responses: { }
      summary: 删除用户
  /v1/user/query/:
    get:
      parameters:
        - description: 用户ID(可选)
          in: query
          name: id
          type: string
        - description: 页面
          in: query
          name: page
          required: true
          type: string
        - description: 页面容量
          in: query
          name: page_size
          required: true
          type: string
      produces:
        - application/json
      responses: { }
      summary: 查询用户
  /v1/user/update/:id:
    put:
      parameters:
        - description: 用户ID(可选)
          in: query
          name: id
          type: string
        - description: 用户名
          in: body
          name: username
          required: true
          schema:
            type: string
        - description: 密码
          in: body
          name: password
          required: true
          schema:
            type: string
        - description: 昵称
          in: body
          name: nickname
          required: true
          schema:
            type: string
        - description: Email
          in: body
          name: email
          required: true
          schema:
            type: string
        - description: 手机号
          in: body
          name: phone
          schema:
            type: string
      produces:
        - application/json
      responses: { }
      summary: 更新用户
swagger: "2.0"
