// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment "Refined_service/biz/router/comment"
	post "Refined_service/biz/router/post"
	user "Refined_service/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	post.Register(r)

	comment.Register(r)

}
